import type { LandingPageConfig } from "@/types/landing-page";

export const TEMPLATE_C_CORPORATE_CONFIG: LandingPageConfig = {
  id: "template-c-corporate",
  organizationId: "demo-org",
  slug: "template-c-corporate",
  status: "published",
  pageTitle: "Senior Financial Analyst bij Fintech Partners | Rotterdam",
  metaDescription: "Analyseer financiële data en adviseer over strategische investeringen. Trusted advisor voor onze investment teams.",
  sections: [
    {
      id: "hero-1",
      type: "hero_corporate",
      order: 0,
      visible: true,
      data: {
        companyName: "Fintech Partners",
        companyTagline: "Investment Excellence",
        headline: "Senior Financial Analyst",
        subheadline: "Analyseer financiële data en adviseer over strategische investeringen. Word een trusted advisor voor onze investment teams.",
        location: "Rotterdam",
        salary: "€5.500 - €7.500 p/m",
        employmentType: "Fulltime",
        primaryCtaLabel: "Solliciteer direct",
        primaryCtaAction: "scroll_to_form",
        secondaryCtaLabel: "Meer over de functie",
      },
    },
    {
      id: "requirements-1",
      type: "requirements",
      order: 1,
      visible: true,
      data: {
        heading: "Wat je meebrengt",
        subheading: "Jouw expertise",
        mustHave: [
          { text: "MSc in Finance, Economics of Accountancy" },
          { text: "Minimaal 4 jaar ervaring in financial analysis" },
          { text: "Uitstekende kennis van Excel en financiële modellen" },
          { text: "CFA Level 2 of hoger (of in opleiding)" },
        ],
        niceToHave: [
          { text: "Ervaring in private equity of VC" },
          { text: "Kennis van fintech sector" },
          { text: "Bloomberg certificatie" },
        ],
      },
    },
    {
      id: "benefits-1",
      type: "benefits",
      order: 2,
      visible: true,
      data: {
        heading: "Wat je krijgt",
        subheading: "Jouw pakket",
        benefits: [
          {
            icon: "💰",
            title: "Salaris €5.500 - €7.500",
            description: "Plus bonus tot 20% van jaarsalaris",
          },
          {
            icon: "📊",
            title: "Jaarlijkse bonus",
            description: "Performance-based tot 20%",
          },
          {
            icon: "🏦",
            title: "Pensioenregeling",
            description: "8% employer contribution",
          },
          {
            icon: "🎓",
            title: "CFA/FRM support",
            description: "Volledige ondersteuning voor certificeringen",
          },
          {
            icon: "🏙️",
            title: "Kantoor met uitzicht",
            description: "Centraal gelegen aan de Maas",
          },
        ],
      },
    },
    {
      id: "application-form-1",
      type: "application_form",
      order: 3,
      visible: true,
      data: {
        heading: "Start je carrière bij Fintech Partners",
        subheading: "Vul onderstaand formulier in",
      },
    },
  ],
  theme: {
    colors: {
      primary: "#6366F1",
      secondary: "#4F46E5",
      accent: "#818CF8",
      background: "#FFFFFF",
      foreground: "#1F2937",
      muted: "#F3F4F6",
      mutedForeground: "#6B7280",
    },
    fonts: {
      heading: "Inter",
      body: "Inter",
    },
    borderRadius: "0.5rem",
    logoUrl: "",
    logoAlt: "Fintech Partners",
  },
  formFields: [
    {
      name: "name",
      label: "Naam",
      type: "text",
      required: true,
      placeholder: "Je volledige naam",
    },
    {
      name: "email",
      label: "E-mail",
      type: "email",
      required: true,
      placeholder: "je@email.nl",
    },
    {
      name: "phone",
      label: "Telefoon",
      type: "tel",
      required: true,
      placeholder: "06 12 34 56 78",
    },
    {
      name: "cv",
      label: "CV",
      type: "file",
      required: true,
      maxFileSizeMB: 5,
      acceptedFileTypes: [".pdf", ".doc", ".docx"],
    },
    {
      name: "linkedin",
      label: "LinkedIn URL",
      type: "url",
      required: false,
      placeholder: "https://linkedin.com/in/...",
    },
    {
      name: "motivation",
      label: "Motivatie",
      type: "textarea",
      required: false,
      placeholder: "Waarom past deze functie bij jou?",
    },
  ],
  formSuccessMessage: "Bedankt! We nemen snel contact op.",
  contact: {
    personName: "Lisa de Jong",
    personRole: "Senior Recruiter",
    personEmail: "demo@kandidatentekort.nl",
    personPhone: "+31 10 456 7890",
  },
  analytics: {},
  cookieConsent: {
    enabled: true,
    privacyPolicyUrl: "#",
    categories: {
      necessary: true,
      analytics: true,
      marketing: true,
    },
  },
  organization: {
    name: "Fintech Partners",
    slug: "fintech-partners",
    logoUrl: "",
    websiteUrl: "https://fintechpartners.nl",
  },
};
